apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hashstrings
  namespace: default
spec:
  maxReplicas: 9
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hashstrings
  targetCPUUtilizationPercentage: 80