apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashstrings
  labels:
    app: hashstrings
spec:
  selector:
    matchLabels:
      app: hashstrings
  replicas: 2
  template:
    metadata:
      labels:
        app: hashstrings
    spec:
      containers:
      - name: hashstrings
        image: asia-southeast1-docker.pkg.dev/kaholo-charlie/kaholo-docker/hashstrings-0.0.2-20220201e
        imagePullPolicy: IfNotPresent
        ports:
          - name: webapi
            containerPort: 8080
        env:
            - name: OBFUSCATIONLEVEL
              value: '355'
        resources:
          requests:
            cpu: "0.2"
          limits:
            cpu: "0.5"
